version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  deploy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker status
          command: docker ps
      - run:
          name: build
          command: docker build -t thibautschaeffer/great-ci:latest .
      - run:
          name: login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push
          command: docker push thibautschaeffer/great-ci:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          # filters:
          #   branches:
          #     only:
          #       - master
          requires:
            - build